export const USER_SIGNIN = 'USER_SIGNIN' // 登录
export const USER_TICKET = 'USER_TICKET' // 登录 ticket
export const USER_SIGNOUT = 'USER_SIGNOUT' // 退出
export const USER_INFO = 'USER_INFO' // 用户信息
export const CHANGE_USER_VERIFY_STATUS = 'CHANGE_USER_VERIFY_STATUS' // 用户信息
export const MSG_COUNT = 'MSG_COUNT' // 消息数量
export const PREV_URL_NAME = 'PREV_URL_NAME' // 记录上一次链接名称
export const CLEAR_PREV_URL_NAME = 'CLEAR_PREV_URL_NAME' // 清空上一次链接
export const MENU_STATUS = 'MENU_STATUS' // 个人中心菜单栏状态
export const HIDE_HEADER = 'HIDE_HEADER' // 是否隐藏头部
export const HIDE_FOOTER = 'HIDE_FOOTER' // 是否隐藏尾部
export const LEFT_WIDTH = 'LEFT_WIDTH' // 个人中心侧边栏宽度
